[project]
name = "otofetch"
version = "1.0.0"
requires-python = ">=3.10,<3.15"

description = "Download your Spotify playlists and songs along with album art and metadata directly from the terminal"
authors = [{ name = "OTAKUWeBer" }]
readme = "README.md"
license = "MIT"

maintainers = [
    { name = "OTAKUWeBer" },
]

keywords = ["spotify", "downloader", "otofetch", "music", "cli"]
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Utilities",
]
dependencies = [
    "spotipy>=2.26.0,<3",
    "spotipyFree>=1.9.13,<2",
    "ytmusicapi>=1.12.1,<2",
    "yt-dlp[default]>=2026.07.04,<2027",
    "mutagen>=1.47.0,<2",
    "rich>=13.9.4,<14",
    "beautifulsoup4>=4.12.3,<5",
    "requests>=2.32.3,<3",
    "rapidfuzz>=3.10.1,<4",
    "python-slugify[unidecode]>=8.0.4,<9",
    "pydantic>=2.9.2,<3",
    "platformdirs>=4.3.6,<5",
    "pykakasi>=2.3.0,<3",
    "syncedlyrics>=1.0.1,<2",
    "soundcloud-v2>=1.6.0,<2",
]

[project.urls]
Homepage = "https://github.com/OTAKUWeBer/OtoFetch"
Repository = "https://github.com/OTAKUWeBer/OtoFetch.git"

[project.scripts]
otofetch = "otofetch:console_entry_point"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

